name = "FCA"
uuid = "9ac0d1d1-ab1e-5a44-888c-d389b307372d"
license = "MIT"
version = "0.2.2"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
GenericLinearAlgebra = "0.1.0"
Optim = "^0.18.1"
julia = "^1"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GenericLinearAlgebra", "ForwardDiff"]
